### ISSUE TITLE
Instruction format encoding is inconsistent with spec

### ISSUE THREAD

**Issue by tclin914** [hanna-kruppe/rvv-llvm#19]
Hi,

I took a look at V-extension implementation of LLVM backend.

I found its instruction format encoding is inconsistent with spec (https://github.com/riscv/riscv-v-spec/).

Does it need to update or wait for more stable spec?

Thanks.

**Comment by rkruppe** [comment]
Yes, the encoding in this repository is still for an older spec and needs updating. The v0.7-draft encoding is stable enough and I want to adopt it, but I am currently working on other changes that will also greatly affect how instructions are defined in the backend, so I've not prioritized updating the encoding beforehand.
