### ISSUE TITLE
Unable to find RISC-V target in llc

### ISSUE THREAD

**Issue by schwarzschild-radius** [hanna-kruppe/rvv-llvm#20]
I tried to build the source and I am unable to find riscv in the registered targets in `llc --version`. I also tried adding RISCV to `LLVM_ENABLE_TARGETS` but it didn't work. Am I doing anything wrong?

**Comment by hanna-kruppe** [comment]
This repository is very outdated, both in the version of the vector spec supported and the LLVM version it's based on. I absolutely do not recommend using this repository for anything in its current state. Much more up-to-date and complete assembler/disassembler support can be found [in SiFive's repository](https://github.com/sifive/riscv-llvm/tree/rvv) (note: branch `rvv`). In the near future, those patches will move upstream (see [D73891](https://reviews.llvm.org/D73891) and [D69987](https://reviews.llvm.org/D69987)) and it's expected that future development will happen directly upstream.

If you still want to give it a spin, or have another reason to build an old LLVM version (prior to release 9.0) with the RISC-V backend enabled, passing `-DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD="RISCV"` to cmake should work.
